server:
    port: 80
spring:
    devtools:
        enabled: true
    http:
        encoding:
          charset: UTF-8
          force: true
          enabled: true
    freemarker:
        template-loader-path:
        - classpath:/templates
        - file:./templates
        cache: false
        checkTemplateLocation: false
        settings:
            classic_compatible: true #处理空值
            template_exception_handler: rethrow
            template_update_delay: 0
            datetime_format: yyyy-MM-dd HH:mm
            number_format: 0.##

    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.106.131.156:3306/test_db_mblog?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
        username: root
        password: password

    jpa:
        database: mysql
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ${site.store.root}/indexes

    servlet:
        multipart:
            max-file-size: 5MB

    mail:
        host: smtp.mtons.com
        username: example@mtons.com
        password: Example2018
        port: 25
        properties:
            mail.smtp.auth: true

# site.theme: [default|card]
site:
    theme: card
    store:
#    本机配置文件路径  上传时windows路径
#      root: d:/data/mblog/
#上传时 Linux配置  路径配置
      root: /data/mblog/
      size: 2